"""Report overview figures: a pipeline schematic and a graphical abstract.

Raised in peer review (comments 4d and 4e): the results read as computational
output rather than as a biological narrative, and a flow chart and graphical
abstract would orient the reader.

Both figures are generated here rather than drawn by hand, so that they use the
same palette and figure settings as every other figure in the report and can be
regenerated by anyone with the repository.

    uv run python scripts/report_figures.py

Writes to results/figures/report_overview/.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

from . import config as cfg

OUT_DIR = cfg.FIGURES_DIR / "report_overview"

# Muted greys for structure, the project palette for anything carrying meaning.
INK = "#333333"
RULE = "#BBBBBB"
FILL_STAGE = "#F2F2F2"
FILL_BRANCH = "#E8EEF7"
FILL_INPUT = "#EEEEEE"


def _save(fig, name: str):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for ext in cfg.FIGURE_FORMATS:
        fig.savefig(OUT_DIR / f"{name}.{ext}", format=ext, dpi=cfg.FIGURE_DPI,
                    bbox_inches="tight", facecolor="white")
    print(f"Saved {name} -> results/figures/report_overview/")
    return fig


def _box(ax, x, y, w, h, text, fill, fontsize=8, bold_first=False, ec=RULE):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.012,rounding_size=0.02",
                                linewidth=0.9, edgecolor=ec, facecolor=fill, zorder=2))
    if bold_first and "\n" in text:
        head, rest = text.split("\n", 1)
        ax.text(x + w / 2, y + h * 0.70, head, ha="center", va="center",
                fontsize=fontsize, fontweight="bold", color=INK, zorder=3)
        ax.text(x + w / 2, y + h * 0.30, rest, ha="center", va="center",
                fontsize=fontsize - 1.1, color="#555555", zorder=3)
    else:
        ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
                fontsize=fontsize, color=INK, zorder=3)


def _arrow(ax, x1, y1, x2, y2, color=RULE, lw=1.1):
    ax.add_patch(FancyArrowPatch((x1, y1), (x2, y2), arrowstyle="-|>",
                                 mutation_scale=11, linewidth=lw,
                                 color=color, zorder=1,
                                 shrinkA=1, shrinkB=1))


# --------------------------------------------------------------------------- #
# Pipeline flow chart
# --------------------------------------------------------------------------- #

def figure_pipeline(name: str = "figure_00_pipeline") -> plt.Figure:
    """Schematic of the analysis, from the eight matrices to the four branches.

    Each stage names the notebook that produces it, so a reader can move from the
    figure to the code without searching.
    """
    fig, ax = plt.subplots(figsize=(9.4, 7.6))
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")

    # --- input ------------------------------------------------------------- #
    _box(ax, 0.20, 0.905, 0.60, 0.075,
         "8 × 10x filtered feature-barcode matrices  ·  GEO GSE202212\n"
         "ctrl 1–2, 3 dpMNU 1–2, 7 dpMNU 1–2, 10 dpMNU 1–2  ·  GRCz11 + EGFP",
         FILL_INPUT, fontsize=8.2, bold_first=True)

    # --- linear stages ----------------------------------------------------- #
    stages = [
        ("Load and annotate metadata\nstep 01  ·  20,097 cells, 25,433 features", 0.795),
        ("Quality control\nstep 02  ·  ≥200 genes, <15% mito  →  15,893 cells (79.1%)", 0.685),
        ("Normalise, HVG, scale\nstep 03  ·  1e4 target, 2,000 HVGs, 2 covariates regressed", 0.575),
        ("PCA, neighbours, UMAP, Leiden\nstep 04  ·  20 PCs, k=15, resolution 0.6  →  20 clusters", 0.465),
        ("Marker discovery and annotation\nstep 05  ·  Wilcoxon on all 22,813 genes  →  13 cell types", 0.355),
    ]
    for text, y in stages:
        _box(ax, 0.14, y, 0.72, 0.082, text, FILL_STAGE, fontsize=8.2, bold_first=True)

    _arrow(ax, 0.50, 0.905, 0.50, 0.877)
    for i in range(len(stages) - 1):
        _arrow(ax, 0.50, stages[i][1], 0.50, stages[i + 1][1] + 0.082)

    # --- fan out to the four analysis branches ----------------------------- #
    _arrow(ax, 0.50, 0.355, 0.50, 0.315)
    ax.plot([0.115, 0.885], [0.315, 0.315], color=RULE, lw=1.1, zorder=1)

    branches = [
        ("Reporter dynamics\nstep 06 · §3.5–3.7\nEGFP within 0.2 pp\nof published", 0.035),
        ("Müller glia states\nstep 06 · §3.8–3.9\nresting vs activated\n23/23 signature genes", 0.265),
        ("Photoreceptors\nstep 06 · §3.10–3.11\nrods not reproduced\ncones reproduced", 0.495),
        ("Published panels\nstep 07 · §4.1\n14 of 18 reproduced", 0.725),
    ]
    for text, x in branches:
        _arrow(ax, x + 0.12, 0.315, x + 0.12, 0.268)
        _box(ax, x, 0.155, 0.24, 0.113, text, FILL_BRANCH, fontsize=7.6, bold_first=True)

    # --- sensitivity analyses ---------------------------------------------- #
    ax.plot([0.155, 0.845], [0.128, 0.128], color=RULE, lw=1.0,
            linestyle=(0, (4, 3)), zorder=1)
    for x in (0.155, 0.845):
        ax.plot([x, x], [0.155, 0.128], color=RULE, lw=1.0,
                linestyle=(0, (4, 3)), zorder=1)
    _arrow(ax, 0.50, 0.128, 0.50, 0.098)
    _box(ax, 0.10, 0.012, 0.80, 0.086,
         "Sensitivity analyses  ·  steps 08 and 09  ·  §4.7 and §4.8\n"
         "Harmony correction and clustering at the published resolution: neither recovers the\n"
         "rod split; the reporter time course is unchanged to two decimal places",
         "#FBF3E4", fontsize=7.8, bold_first=True, ec="#D9C18E")

    ax.text(0.5, 1.0, "Analysis pipeline", ha="center", va="top",
            fontsize=12.5, fontweight="bold", color=INK)
    fig.tight_layout()
    return _save(fig, name)


# --------------------------------------------------------------------------- #
# Graphical abstract
# --------------------------------------------------------------------------- #

def figure_graphical_abstract(name: str = "figure_00_graphical_abstract") -> plt.Figure:
    """One-page summary: the model, the reporter result, and what reproduced."""
    fig = plt.figure(figsize=(10.2, 5.4))
    gs = fig.add_gridspec(2, 3, height_ratios=[1.05, 1.0],
                          hspace=0.42, wspace=0.30,
                          left=0.055, right=0.975, top=0.845, bottom=0.075)

    # --- A. the model ------------------------------------------------------ #
    ax = fig.add_subplot(gs[0, 0])
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    ax.set_title("A   Injury model", fontsize=9.5, loc="left", color=INK, pad=6)

    layers = [("outer nuclear layer\nrods, UV cones", 0.72, cfg.CELL_TYPE_COLORS["Rods"]),
              ("inner nuclear layer\nbipolar, amacrine, Müller glia", 0.45,
               cfg.CELL_TYPE_COLORS["Muller glia"]),
              ("ganglion cell layer", 0.20, cfg.CELL_TYPE_COLORS["Retinal ganglion cells"])]
    for label, y, colour in layers:
        ax.add_patch(FancyBboxPatch((0.06, y), 0.88, 0.16,
                                    boxstyle="round,pad=0.006,rounding_size=0.02",
                                    facecolor=colour, alpha=0.32, edgecolor=colour,
                                    linewidth=1.0))
        ax.text(0.5, y + 0.08, label, ha="center", va="center", fontsize=7.2, color=INK)
    ax.annotate("MNU", xy=(0.5, 0.90), xytext=(0.5, 0.985), ha="center",
                fontsize=8.5, fontweight="bold", color="#B22182",
                arrowprops=dict(arrowstyle="-|>", color="#B22182", lw=1.4))
    ax.text(0.5, 0.055, "photoreceptor ablation → Müller glia activation",
            ha="center", fontsize=7.4, style="italic", color="#555555")

    # --- B. reporter time course ------------------------------------------ #
    ax = fig.add_subplot(gs[0, 1])
    ours = [0.56, 5.40, 2.45, 2.80]
    paper = [0.54, 5.40, 2.64, 2.66]
    x = np.arange(4)
    ax.plot(x, paper, "o--", color="#999999", lw=1.6, ms=6,
            label="Bise et al. (Seurat)", zorder=2)
    ax.plot(x, ours, "o-", color=cfg.CELL_TYPE_COLORS["Muller glia"], lw=2.2, ms=7,
            label="this reanalysis (Scanpy)", zorder=3)
    ax.set_xticks(x)
    ax.set_xticklabels([cfg.CONDITION_LABELS[c] for c in cfg.CONDITION_ORDER], fontsize=7.6)
    ax.set_ylabel("% EGFP-positive cells", fontsize=8)
    ax.set_title("B   careg:EGFP reproduces within 0.2 pp", fontsize=9.5, loc="left",
                 color=INK, pad=6)
    ax.legend(frameon=False, fontsize=7, loc="upper right")
    ax.tick_params(labelsize=7.5)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    # --- C. cell types ----------------------------------------------------- #
    ax = fig.add_subplot(gs[0, 2])
    counts = {"Rods": 4314, "Cones": 2614, "Muller glia": 1807, "Bipolar cells": 1758,
              "Amacrine cells": 1274, "Rods (low quality)": 1062, "RPE": 847,
              "Horizontal cells": 712, "Microglia": 661}
    names = list(counts)[::-1]
    vals = [counts[n] for n in names]
    ax.barh(names, vals, color=[cfg.CELL_TYPE_COLORS[n] for n in names], height=0.72)
    ax.set_xlabel("cells", fontsize=8)
    ax.set_title("C   13 populations from 15,893 cells", fontsize=9.5, loc="left",
                 color=INK, pad=6)
    ax.tick_params(labelsize=7)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    ax.text(0.98, 0.04, "+ 4 smaller populations", transform=ax.transAxes,
            ha="right", fontsize=6.6, style="italic", color="#777777")

    # --- D. what reproduced ------------------------------------------------ #
    ax = fig.add_subplot(gs[1, :])
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
    ax.set_title("D   Which conclusions survive a change of method",
                 fontsize=9.5, loc="left", color=INK, pad=4)

    cards = [
        ("REPRODUCED", "#117733",
         "Reporter time course, within 0.2 pp at every timepoint\n"
         "Müller glia enriched 3.75×, holding 42.6% of EGFP+ cells\n"
         "All 23 tested genes of the published MG signature\n"
         "Cone arr3a/arr3b inversion, exactly", 0.015),
        ("NOT REPRODUCED", "#CC3311",
         "Rod immature/mature paralog inversion\n"
         "  · fails at resolution 0.6 and at 0.2\n"
         "  · fails under Harmony batch correction\n"
         "  · no rhol-high population exists in these data", 0.345),
        ("ADDED HERE", "#0077BB",
         "Reporter survives depth stratification: 0% → 54.3%\n"
         "Stressed rod population supports the capture-bias\n"
         "  mechanism the published work inferred\n"
         "DE directional skew tracks sequencing-depth imbalance", 0.675),
    ]
    for head, colour, body, x in cards:
        ax.add_patch(FancyBboxPatch((x, 0.06), 0.31, 0.80,
                                    boxstyle="round,pad=0.012,rounding_size=0.03",
                                    facecolor="white", edgecolor=colour, linewidth=1.5))
        ax.text(x + 0.155, 0.755, head, ha="center", va="center", fontsize=8.2,
                fontweight="bold", color=colour)
        ax.text(x + 0.022, 0.60, body, ha="left", va="top", fontsize=7.0,
                color=INK, linespacing=1.6)

    fig.suptitle("Independent Scanpy reanalysis of careg:EGFP dynamics in the "
                 "regenerating zebrafish retina",
                 fontsize=11.5, fontweight="bold", color=INK, y=0.965)
    fig.text(0.5, 0.912, "Bise et al. 2023 · GEO GSE202212 · 15,893 cells · "
             "control, 3, 7 and 10 days post-MNU",
             ha="center", fontsize=8, color="#666666")
    return _save(fig, name)


if __name__ == "__main__":
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from scripts import plotting
    plotting.set_style()
    figure_pipeline()
    figure_graphical_abstract()
    print("\nInsert figure_00_pipeline in Methods (§2) and "
          "figure_00_graphical_abstract after the Abstract.")
