"""Generate the seven analysis notebooks from source-controlled cell definitions.

Run from the repository root:

    python tools/build_notebooks.py

Keeping notebooks generated rather than hand-edited means the executed .ipynb files
(with their outputs) can stay out of Git while the *content* stays reviewable as
plain text in this file. Regenerating never overwrites an executed notebook unless
--force is passed.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK_DIR = REPO_ROOT / "notebooks"

KERNEL = {
    "kernelspec": {
        "display_name": "Python 3 (retina)",
        "language": "python",
        "name": "retina",
    },
    "language_info": {"name": "python", "version": "3.11"},
}

# Prepended to every code notebook so imports resolve from notebooks/.
BOOTSTRAP = '''\
import sys
from pathlib import Path

# Make the repository root importable regardless of where Jupyter was launched.
REPO_ROOT = Path.cwd()
if not (REPO_ROOT / "scripts").exists():
    REPO_ROOT = REPO_ROOT.parent
assert (REPO_ROOT / "scripts").exists(), (
    f"Cannot locate the repository root from {Path.cwd()}. "
    "Launch JupyterLab from the repository root."
)
sys.path.insert(0, str(REPO_ROOT))

from scripts import config as cfg
from scripts import io_utils, qc, preprocessing, clustering, annotation, egfp_analysis, plotting

cfg.ensure_directories()
plotting.set_style()
SEED = io_utils.set_seeds()
print(f"Repository root: {REPO_ROOT}")
print(f"Random seed: {SEED}")
'''


def md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source.rstrip().splitlines(keepends=True)}


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source.rstrip().splitlines(keepends=True),
    }


def write_notebook(filename: str, cells: list[dict], force: bool = False) -> Path:
    path = NOTEBOOK_DIR / filename
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        existing = json.loads(path.read_text())
        has_output = any(c.get("outputs") for c in existing.get("cells", []))
        if has_output:
            print(f"SKIP {filename} (already executed; pass --force to overwrite)")
            return path
    notebook = {"cells": cells, "metadata": KERNEL, "nbformat": 4, "nbformat_minor": 5}
    path.write_text(json.dumps(notebook, indent=1))
    print(f"wrote {filename} ({len(cells)} cells)")
    return path


# =========================================================================== #
# step_0.0 -- environment
# =========================================================================== #

NB_00 = [
    md("""
# Step 0.0 — Environment management with uv

**Purpose.** Create a reproducible Python environment so that every figure and
table in this project can be regenerated by someone else from a clean clone.

`uv` is used instead of conda: it resolves and installs from a lockfile in
seconds, and it pins transitive dependencies, which conda's `environment.yml`
does not do by default.

This notebook is documentation with runnable checks. The shell commands are shown
for copying into a terminal; only the verification cells are meant to be executed
inside the kernel.
"""),
    md("""
## 1. Install uv

```bash
# Linux / macOS / WSL
curl -LsSf https://astral.sh/uv/install.sh | sh

# Windows PowerShell
powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"

# or, if you already have pip
pip install uv
```

## 2. Create the environment and install dependencies

From the repository root:

```bash
uv venv --python 3.11
source .venv/bin/activate            # Windows: .venv\\Scripts\\Activate.ps1

uv pip install -r requirements.txt   # exact pinned versions
# or, for a fresh resolve from pyproject.toml:
uv pip install -e .
```

## 3. Register the Jupyter kernel

```bash
python -m ipykernel install --user --name retina --display-name "Python 3 (retina)"
```

Then pick **Python 3 (retina)** as the kernel in JupyterLab. If the notebooks run
against the system Python instead, every version number recorded below is wrong.

## 4. Re-pin after any change

```bash
uv pip freeze > requirements.txt
git add requirements.txt && git commit -m "Update pinned dependencies"
```

## 5. Run non-interactively

```bash
uv run jupyter lab
uv run python tools/build_notebooks.py
```
"""),
    md("""
## Package list and why each one is here

| Package | Why it is needed |
|---|---|
| `scanpy` | the analysis framework: QC, normalisation, PCA/UMAP, Leiden, DE |
| `anndata` | the on-disk and in-memory data structure (`.h5ad`) |
| `numpy`, `pandas`, `scipy` | arrays, tables, sparse matrices |
| `matplotlib`, `seaborn` | figures |
| `jupyter`, `ipykernel` | notebook interface and kernel registration |
| `gseapy` | GO / pathway enrichment on marker lists (the Python stand-in for the paper's topGO) |
| `igraph`, `leidenalg` | **required backend for `sc.tl.leiden`** — Scanpy does not vendor a Leiden implementation, so clustering fails without them |
| `h5py` | `.h5ad` read/write (pulled in by anndata, pinned so checkpoints stay loadable) |

Nothing else is installed by default. `harmonypy` is needed **only** if the Step 04
batch diagnostics justify integration; installing it is a deliberate act that must
be recorded in the Methods section, not a default.
"""),
    code(BOOTSTRAP),
    code('''\
# Verify the environment and write the reproducibility record.
versions_path = io_utils.write_versions()
print(f"\\nSession info written to {versions_path.relative_to(cfg.REPO_ROOT)}")
'''),
    code('''\
# Confirm the Leiden backend is importable BEFORE spending an hour on preprocessing.
try:
    import leidenalg  # noqa: F401
    import igraph     # noqa: F401
    print("Leiden backend available.")
except ImportError as exc:
    raise ImportError(
        "sc.tl.leiden needs 'leidenalg' and 'igraph'. Install with:\\n"
        "    uv pip install leidenalg igraph\\n"
        "and re-pin with: uv pip freeze > requirements.txt"
    ) from exc
'''),
    md("""
### What to check before continuing

- [ ] The active kernel is **Python 3 (retina)**, not the system Python.
- [ ] `docs/session_info.json` exists and lists a Scanpy version.
- [ ] The Leiden backend imported without error.
- [ ] `data/` contains the eight sample folders (checked in Step 01).
"""),
]


# =========================================================================== #
# step_01 -- loading
# =========================================================================== #

NB_01 = [
    md("""
# Step 01 — Loading libraries and the 10x data

**Purpose.** Read the eight Cell Ranger filtered matrices into one AnnData object
with clean, correctly ordered metadata, and establish two facts the rest of the
project depends on:

1. whether the **EGFP transgene is present as a feature** in the count matrices;
2. how many cells and genes each sample contributes *before* any filtering.

**Biological context.** Each sample is one 10x run from a pool of dissected adult
zebrafish retinas: two uninjured controls and two replicates each at 3, 7 and 10
days post-MNU. Condition and sequencing run are fully confounded by design — a
limitation to carry through to the Discussion, not something to correct away.
"""),
    code(BOOTSTRAP),
    md("""
## 1. Discover and validate the sample directories

Paths are discovered relative to the repository root. Nothing is hard-coded, so
the notebook runs unchanged on another machine.
"""),
    code('''\
sample_dirs = io_utils.discover_samples()
expected = io_utils.report_expected_samples(sample_dirs)
display(expected)

missing = expected.loc[expected["expected"] & ~expected["found"], "sample"].tolist()
if missing:
    print(f"WARNING: expected sample(s) not found: {missing}")
    print("The analysis can proceed, but every proportion and time-course result "
          "must state which samples were unavailable.")
'''),
    code('''\
# Confirm each folder holds all three Cell Ranger files before reading anything.
for sample_dir in sample_dirs:
    io_utils.validate_sample_dir(sample_dir)
print("All sample directories contain barcodes.tsv.gz, features.tsv.gz and matrix.mtx.gz.")
'''),
    md("""
## 2. Load and concatenate

`load_all_samples` reads each matrix, attaches `sample` / `condition` /
`replicate` / `timepoint` / `batch`, prefixes barcodes with the sample name so
they stay unique, and concatenates with `join="outer"`.

`condition` is made an **ordered categorical** (`ctrl → 3dp → 7dp → 10dp`) at load
time. Left as a string, `"10dp"` sorts before `"3dp"` and every downstream plot
would silently show the time course out of order.
"""),
    code('''\
adata, per_sample = io_utils.load_all_samples()
display(per_sample)
'''),
    code('''\
# Assertions on the assumptions the rest of the workflow relies on.
assert adata.n_obs > 0, "No cells loaded."
assert adata.obs_names.is_unique, "Barcodes are not unique."
for col in ("sample", "condition", "replicate", "timepoint", "batch"):
    assert col in adata.obs, f"Missing metadata column: {col}"
assert list(adata.obs["condition"].cat.categories) == cfg.CONDITION_ORDER, (
    "Condition categories are not in biological time order."
)
print("Metadata checks passed.")
print(adata.obs.groupby(["condition", "sample"], observed=True).size().to_string())
'''),
    md("""
## 3. Is EGFP in the matrix?

The transgene is only countable if it was added to the Cell Ranger reference
before alignment. The feature name is **detected, not assumed** — capitalisation
varies between references (`EGFP`, `eGFP`, `GFP`).

If no EGFP-like feature exists, research question 3 and Figure 4 cannot be
answered from this matrix. The correct response is to report that, not to
substitute a proxy gene.
"""),
    code('''\
egfp_name = io_utils.find_egfp_feature(adata)

if egfp_name is not None:
    counts = preprocessing.get_expression(adata, egfp_name, layer="X")
    n_pos = int((counts > 0).sum())
    print(f"Cells with >0 EGFP counts (pre-QC): {n_pos} / {adata.n_obs} "
          f"({100 * n_pos / adata.n_obs:.2f}%)")
    print(f"Max EGFP counts in a single cell: {counts.max():.0f}")
    display(
        adata.obs.assign(egfp_pos=counts > 0)
        .groupby("condition", observed=True)["egfp_pos"]
        .agg(["sum", "size"])
        .assign(percent=lambda d: (100 * d["sum"] / d["size"]).round(2))
    )
'''),
    md("""
### Interpretation

Read the per-condition EGFP table above before going further. The paper reports
EGFP transcripts in ~0.5% of control cells rising to ~5% at 3 dpMNU and settling
near 2.6% at 7 and 10 dpMNU. A **control value near zero and a rise after injury**
is the expected shape. If controls show a high EGFP rate, suspect index hopping or
sample swapping and investigate before interpreting anything else.
"""),
    code('''\
# Save the loading checkpoint and the sample-level table.
io_utils.save_table(per_sample, "cell_counts_by_sample_raw.csv")
io_utils.save_checkpoint(adata, "loaded")
'''),
    md("""
### What to check before continuing

- [ ] Eight samples discovered; any missing sample is recorded.
- [ ] Cell counts per sample are in a plausible range (thousands, not tens).
- [ ] `condition` categories print as `['ctrl', '3dp', '7dp', '10dp']`.
- [ ] EGFP presence/absence is recorded — this decides whether Figure 4 is possible.
- [ ] `results/01_loaded.h5ad` was written.
"""),
]


# =========================================================================== #
# step_02 -- QC
# =========================================================================== #

NB_02 = [
    md("""
# Step 02 — Quality control and cell filtering

**Purpose.** Remove empty droplets, damaged cells and undetectable genes, using
thresholds that are looked at before they are applied.

**Why the prefixes differ from human data.** Zebrafish gene symbols are lower
case: mitochondrial genes begin `mt-`, ribosomal protein genes `rps`/`rpl`,
haemoglobins `hba`/`hbb`/`hb-`. Copying a human QC snippet (`MT-`) silently
matches nothing, `pct_counts_mt` comes out as zero for every cell, and the
mitochondrial filter quietly does nothing.

**Baseline thresholds (from the project guide).**
`min_genes = 200`, `min_cells = 3`, `pct_counts_mt < 15%`.
These stay as defaults. Any change is made in `scripts/config.py`, recorded in
`cfg.PARAM_OVERRIDES`, and justified here from the diagnostics.
"""),
    code(BOOTSTRAP),
    code('''\
adata = io_utils.load_checkpoint("loaded")
'''),
    md("""
## 1. Flag gene families and compute QC metrics

Nothing is filtered in this section — the metrics are needed to judge the
thresholds.
"""),
    code('''\
adata = qc.annotate_qc(adata)
display(adata.obs[["total_counts", "n_genes_by_counts",
                   "pct_counts_mt", "pct_counts_ribo", "pct_counts_hb"]].describe().round(2))
'''),
    code('''\
qc_before = qc.qc_summary_table(adata, stage="before_filter")
display(qc_before)
'''),
    md("""
## 2. Figure 1 — QC diagnostics

Violins by sample with the thresholds drawn on, a counts-vs-genes scatter coloured
by mitochondrial content, and the filtering waterfall.
"""),
    code('''\
diagnostics = qc.threshold_diagnostics(adata)
display(diagnostics)

for note in qc.interpret_thresholds(diagnostics):
    print(f"- {note}")
'''),
    md("""
### Interpretation — do the baseline thresholds fit these data?

Work through these before filtering:

1. **Is the loss even across samples?** A much larger loss in the injured samples
   is expected (MNU damages the outer nuclear layer, and damaged cells dissociate
   into stressed, high-mitochondrial singlets) — but it means the surviving cell
   population is not sampled identically across conditions, which propagates into
   every proportion in Figure 5.
2. **Does the mitochondrial distribution have a clear shoulder?** If the bulk of
   cells sit well under 15% and a distinct tail sits above, the threshold is doing
   what it should. If the distribution is smooth through 15%, the cut is arbitrary
   and the number of cells it removes should be reported as a sensitivity note.
3. **Is anything lost at `min_genes = 200`?** Cell Ranger's *filtered* matrix has
   already removed most empty droplets, so this filter often removes very little.
   That is normal, not a bug.
"""),
    code('''\
adata_filtered, filter_log = qc.filter_cells_and_genes(adata)
display(filter_log)
'''),
    code('''\
fig = plotting.figure_01_qc(adata, filter_log=filter_log)
'''),
    code('''\
import pandas as pd

qc_after = qc.qc_summary_table(adata_filtered, stage="after_filter")
qc_summary = pd.concat([qc_before, qc_after], ignore_index=True)
io_utils.save_table(qc_summary, "qc_summary.csv")
display(qc_after)
'''),
    code('''\
cell_counts = qc.per_sample_cell_counts(adata_filtered)
io_utils.save_table(cell_counts, "cell_counts_by_sample.csv")
display(cell_counts)
'''),
    md("""
## 3. Transgene detectability after QC

Recorded here so the Methods section can state the EGFP detection rate on the
filtered data, which is the population every later figure uses.
"""),
    code('''\
egfp_name = io_utils.find_egfp_feature(adata_filtered, verbose=False)
print(qc.egfp_qc_note(adata_filtered, egfp_name))
'''),
    code('''\
adata = adata_filtered
io_utils.save_checkpoint(adata, "qc_filtered")
'''),
    md("""
### What to check before continuing

- [ ] `pct_counts_mt` is **not** identically zero (if it is, the `mt-` prefix matched nothing).
- [ ] Total retained cells is a sensible fraction of the input (roughly 80–95% is typical here).
- [ ] Cell loss per sample is recorded, and any condition-dependent loss is noted for the Discussion.
- [ ] `tables/qc_summary.csv` and `tables/cell_counts_by_sample.csv` exist.
- [ ] Figure 1 saved as PNG **and** PDF.
"""),
]


# =========================================================================== #
# step_03 -- normalisation
# =========================================================================== #

NB_03 = [
    md("""
# Step 03 — Normalisation, HVG selection and scaling

**Purpose.** Put the cells on a comparable scale, pick the genes that carry
between-cell signal, and produce the matrix that PCA will consume — while keeping
the raw counts and the log-normalised values intact for everything else.

## The four representations, and why mixing them up matters

| Where | What it holds | Correct use |
|---|---|---|
| `adata.layers["counts"]` | raw integer UMIs | EGFP positivity call; any count-based model |
| `adata.layers["lognorm"]` | normalised + `log1p` | **all differential expression, dotplots, violins, any quoted expression value** |
| `adata.raw` | frozen lognorm over *all* genes | plotting genes that were not selected as HVGs |
| `adata.X` after scaling | z-scores over HVGs, clipped at ±10 | PCA / neighbours / UMAP **only** |

Running `rank_genes_groups` on the scaled matrix is the classic error: it tests
z-scores rather than expression, and restricts the result to 2,000 genes.

## What the paper did instead

Bise et al. used **SCTransform** — a regularised negative-binomial model whose
Pearson residuals replace log-normalisation — with mitochondrial and ribosomal
percentage regressed out during normalisation, followed by Seurat's anchor-based
integration.

This pipeline uses `normalize_total` + `log1p`, which is what the project guide
specifies. **That is a different estimator, not a re-implementation.** SCTransform
downweights highly expressed genes differently and typically yields somewhat
different HVGs and cluster boundaries. See `docs/method_comparison.md`. The
closest Scanpy analogue is
`sc.experimental.pp.normalize_pearson_residuals`; it is not used here because the
guide's baseline takes precedence and switching would be an undocumented change.
"""),
    code(BOOTSTRAP),
    code('''\
import pandas as pd
adata = io_utils.load_checkpoint("qc_filtered")
'''),
    md("""
## 1. Preserve counts, then normalise and log-transform
"""),
    code('''\
adata = preprocessing.normalize_and_log(adata)
print(f"Layers now present: {preprocessing.layer_names(adata)}")
print(f".raw holds {adata.raw.n_vars} genes (all genes, log-normalised)")
'''),
    md("""
## 2. Highly variable genes

2,000 HVGs, selected **per sample** and combined (`batch_key="sample"`). Without
the batch key, a gene that is variable only in one injured sample can be selected
on the strength of that one run.
"""),
    code('''\
adata = preprocessing.select_hvgs(adata)
fig = plotting.figure_hvg(adata)
'''),
    code('''\
# Are the canonical markers we need for annotation inside the HVG set?
# They do not have to be: .raw keeps every gene available for plotting and DE.
hvg_genes = set(adata.var_names[adata.var["highly_variable"]])
for cell_type, genes in cfg.MARKERS_GUIDE.items():
    present = [g for g in genes if g in adata.var_names]
    in_hvg = [g for g in present if g in hvg_genes]
    print(f"{cell_type:<28} present: {len(present)}/{len(genes)}   in HVG set: {len(in_hvg)}")
'''),
    md("""
## 3. Preserve the transgene before subsetting

`regress_and_scale` subsets to the 2,000 HVGs, which removes every other gene from
`.X` and the layers. EGFP is a single-copy transgene and is **not** guaranteed to
be selected as highly variable, so its raw counts are copied into `.obs` first.
This changes no analysis — it keeps a number reachable that Step 06 depends on.

(`.raw` also retains all genes, so the sub-analyses in Step 06 rebuild from there.)
"""),
    code('''\
egfp_name = io_utils.find_egfp_feature(adata, verbose=False)
if egfp_name is not None:
    preprocessing.preserve_gene_counts_in_obs(adata, egfp_name, obs_key="egfp_counts")
else:
    print("No EGFP feature to preserve.")
'''),
    md("""
## 4. Regress technical covariates, then scale

**Documented deviation.** The guide's snippet calls `regress_out` on the full gene
set. We keep the same covariates (`total_counts`, `pct_counts_mt`) and keep the
step enabled, but run it *after* subsetting to HVGs. The genes dropped are exactly
the ones discarded before PCA anyway, so the result is unchanged while the runtime
falls from hours to minutes on ~50k cells. Set
`cfg.REGRESS_ON_HVG_SUBSET = False` to reproduce the guide's literal order.

Note that regressing `total_counts` after library-size normalisation is partly
redundant; it is retained because it is the prescribed baseline.
"""),
    code('''\
adata = preprocessing.regress_and_scale(adata)
print(f"adata.X is now scaled: shape {adata.shape}, "
      f"mean {adata.X.mean():.3f}, sd {adata.X.std():.3f}")
'''),
    code('''\
summary = preprocessing.preprocessing_summary(adata)
io_utils.save_table(summary, "preprocessing_summary.csv")
display(summary.T)
'''),
    code('''\
io_utils.save_checkpoint(adata, "preprocessed")
'''),
    md("""
### What to check before continuing

- [ ] `layers['counts']` still holds integers (`adata.layers['counts'].max()` is a whole number).
- [ ] `adata.raw` exists and covers all genes, not just the HVGs.
- [ ] The scaled `adata.X` has mean ≈ 0 and sd ≈ 1.
- [ ] The HVG plot shows a normal-looking mean/dispersion cloud, not a degenerate line.
- [ ] You can state in one sentence which matrix you will use for DE (`lognorm` / `.raw`).
"""),
]


# =========================================================================== #
# step_04 -- PCA / UMAP / Leiden
# =========================================================================== #

NB_04 = [
    md("""
# Step 04 — PCA, neighbours, UMAP and Leiden clustering

**Purpose.** Reduce the scaled HVG matrix to a small number of components, build a
neighbour graph, embed it for visualisation, and partition it into clusters that
Step 05 will annotate.

**Baseline:** `n_pcs = 20`, `n_neighbors = 15`, Leiden `resolution = 0.6`.

**On integration.** The paper integrated across samples (Seurat, dims = 30). We do
**not** integrate by default. In this design each timepoint is its own pair of 10x
runs, so `sample` and `condition` are confounded: correcting on `sample` can
delete the injury response along with the batch effect. The decision is made from
the diagnostics below and written down either way.
"""),
    code(BOOTSTRAP),
    code('''\
import pandas as pd
adata = io_utils.load_checkpoint("preprocessed")
'''),
    md("""
## 1. PCA and how many components to keep
"""),
    code('''\
adata = clustering.run_pca(adata)
variance_table = clustering.pca_variance_table(adata)
suggested = clustering.suggest_n_pcs(adata)
fig = plotting.figure_pca_variance(variance_table, n_pcs_used=cfg.N_PCS_NEIGHBORS)
display(variance_table.head(30).round(4))
'''),
    md("""
### Interpretation

The elbow heuristic is advisory. Keep `n_pcs = 20` unless the plot clearly
disagrees — and if you change it, edit `cfg.N_PCS_NEIGHBORS`, record it in
`cfg.PARAM_OVERRIDES`, and say so in the Methods section. Too few PCs merges
genuinely distinct cell types; too many mostly adds noise and slows the graph
build without changing the biology much.
"""),
    md("""
## 2. Batch diagnostics — decide about integration on evidence

For each of the first 20 PCs, how much variance is explained by `condition`
(biology + confounded run) versus `replicate` (technical only)? Replicate is the
cleaner read on batch: replicates within a condition differ *only* technically.
"""),
    code('''\
diag = clustering.batch_diagnostics(adata)
for note in clustering.interpret_batch_diagnostics(diag):
    print(f"- {note}")

io_utils.save_table(
    diag.groupby("factor")["variance_explained"].mean().round(4).reset_index(),
    "batch_diagnostics.csv",
)
'''),
    code('''\
# Integration is OFF unless config says otherwise. Flip cfg.USE_INTEGRATION only
# with a written justification, and keep the uncorrected UMAP for comparison.
use_rep = None
if cfg.USE_INTEGRATION:
    use_rep = clustering.run_integration(adata)
    print(f"Integration applied; downstream graph uses representation '{use_rep}'.")
else:
    print("No integration applied. Rationale recorded in the Methods section.")
'''),
    md("""
## 3. Neighbour graph, UMAP and Leiden
"""),
    code('''\
adata = clustering.run_neighbors_umap(adata, use_rep=use_rep)
adata = clustering.run_leiden(adata)
print(adata.obs[cfg.LEIDEN_KEY].value_counts().sort_index().to_string())
'''),
    md("""
## Figure 2 — global cell atlas
"""),
    code('''\
fig = plotting.figure_02_umap(adata)
fig = plotting.figure_02_split_by_condition(adata)
'''),
    md("""
### Interpretation — is this clustering plausible?

Three things to look at, in this order:

1. **Does the UMAP separate into a few large, well-separated islands?** Retina is
   dominated numerically by photoreceptors, so a very large rod territory with
   smaller satellites is the expected shape, not a warning sign.
2. **Do clusters mix across samples?** Panel C should show most clusters
   containing cells from several samples. A cluster made almost entirely of one
   run is a technical-artefact candidate — flagged automatically below.
3. **Does condition structure look biological?** Injured cells shifting *within* a
   cell-type island (a stress/activation gradient) is biology. Whole clusters that
   exist only in one timepoint need a marker-based explanation before they can be
   called a new cell state.
"""),
    code('''\
flagged = clustering.flag_single_sample_clusters(adata)
display(flagged)

composition = clustering.cluster_composition(adata)
io_utils.save_table(composition, "cluster_composition.csv")
'''),
    md("""
## 4. Resolution stability

Evidence that resolution 0.6 is a reasonable operating point rather than a lucky
pick. The reported clustering stays at 0.6.
"""),
    code('''\
sweep = clustering.resolution_sweep(adata)
io_utils.save_table(sweep, "leiden_resolution_sweep.csv")
display(sweep)
'''),
    code('''\
io_utils.save_checkpoint(adata, "clustered")
'''),
    md("""
### What to check before continuing

- [ ] Cluster count is in a workable range (roughly 10–25 for adult retina at res 0.6).
- [ ] No cluster is >90% one sample, or those that are have been investigated.
- [ ] The integrate / do-not-integrate decision is written down with its reason.
- [ ] Figure 2 saved as PNG and PDF.
- [ ] `results/04_clustered.h5ad` exists.
"""),
]


# =========================================================================== #
# step_05 -- annotation
# =========================================================================== #

NB_05 = [
    md("""
# Step 05 — Cell type annotation and marker discovery

**Purpose.** Assign a cell type to every cluster, with the evidence and the
confidence written down.

**Research question 1** is answered here: which major retinal cell types are
present.

## Rules this notebook enforces

1. **No invented genes.** Every marker is checked against `adata.var_names`; a
   missing marker is reported as unavailable and the panel proceeds without it.
2. **No single-marker calls.** Each assignment needs concordant evidence: a panel
   score, a data-driven marker list, and a check for conflicting markers.
3. **No forced labels.** A cluster whose evidence is ambiguous is annotated
   `Unresolved` (or `Candidate X`) and keeps that label in every figure. An honest
   "Unresolved" is defensible at a viva; a confident wrong label is not.
4. **Identity ≠ activation.** `pcna`/`mki67` say a cell is cycling, `EGFP` says a
   reporter is active. Neither is an identity marker. A cluster is Müller glia
   because of `rlbp1a`/`glula`/`slc1a3b`, not because it is EGFP-positive.
"""),
    code(BOOTSTRAP),
    code('''\
import pandas as pd
adata = io_utils.load_checkpoint("clustered")
'''),
    md("""
## 1. Data-driven markers per cluster

Wilcoxon rank-sum on the **log-normalised** values (via `.raw`), not on the scaled
matrix.
"""),
    code('''\
adata = annotation.rank_markers(adata)
marker_df = annotation.markers_to_dataframe(adata)
io_utils.save_table(marker_df, "marker_genes.csv")
display(annotation.top_markers_per_cluster(marker_df, n=10))
'''),
    md("""
## 2. Canonical panel scores

Two panels: the one supplied by the project guide, and a supplementary set drawn
from Bise et al. for the cell types the guide's panel does not cover (horizontal
cells, oligodendrocytes, erythrocytes, pericytes, RPE).
"""),
    code('''\
print("=== Guide panel ===")
adata = annotation.score_panels(adata, cfg.MARKERS_GUIDE, prefix="score")
print("\\n=== Supplementary panel (Bise et al.) ===")
adata = annotation.score_panels(adata, cfg.MARKERS_PAPER, prefix="paper")
'''),
    code('''\
score_matrix = annotation.panel_score_matrix(adata, prefix="score")
display(score_matrix.style.background_gradient(axis=1, cmap="RdBu_r"))

suggestions = annotation.best_and_runner_up(score_matrix)
display(suggestions)
'''),
    code('''\
paper_matrix = annotation.panel_score_matrix(adata, prefix="paper")
display(paper_matrix.style.background_gradient(axis=1, cmap="RdBu_r"))
'''),
    md("""
### How to read the suggestion table

`suggested_confidence` is arithmetic, not judgement: it reflects the margin
between the best and second-best panel score. Use it to decide where to look
harder, then set the confidence yourself in the annotation dictionary below.

A small margin usually means one of three things, and they need different
responses:

- **Two related types** (e.g. rod vs cone) — resolve with individual marker
  expression, not the panel score.
- **A doublet cluster** — high on two unrelated panels at once; check whether it
  also has elevated counts and gene numbers.
- **A state rather than a type** (e.g. activated MG) — high on an identity panel
  *and* on activation markers. Annotate the identity, and record the state
  separately.
"""),
    code('''\
# Individual marker expression per cluster, for resolving the ambiguous ones.
all_guide_genes = [g for genes in cfg.MARKERS_GUIDE.values() for g in genes]
expr = annotation.mean_marker_expression(adata, all_guide_genes)
display(expr.style.background_gradient(axis=0, cmap="viridis"))
'''),
    md("""
## Figure 3A/B — marker dotplot and heatmap
"""),
    code('''\
fig = plotting.figure_03_markers(adata, cfg.MARKERS_GUIDE)
fig = plotting.figure_03_heatmap(adata, cfg.MARKERS_GUIDE)
'''),
    md("""
## 3. The annotation itself

**This cell is where your scientific judgement is recorded, and it is the one you
must be able to defend line by line.**

Fill in one entry per cluster. The template below is a *scaffold*: the cluster
numbers and the cell types are placeholders. Replace them using the tables above.
`build_annotation_table` refuses to run if any cluster is missing, if a rationale
is empty, or if confidence is not one of high/medium/low.

Expected from this dataset, based on the paper: rods dominate; cones, Müller glia,
bipolar, amacrine, horizontal cells, microglia, oligodendrocytes, erythrocytes,
pericytes and RPE are present in smaller numbers. **Retinal ganglion cells were
essentially not captured by Bise et al.** — if no cluster is `rbpms2b`-high here
either, that is a reproducible finding to report, not a failure to annotate.
"""),
    code('''\
# TEMPLATE — replace every entry using the evidence tables above.
# Delete this line once you have gone through all clusters yourself.
annotations = {
    "0": {
        "cell_type": "Rods",
        "positive_markers": ["rho", "gnat1", "nr2e3"],
        "conflicting_markers": [],
        "confidence": "high",
        "rationale": "Largest cluster; top data-driven markers are phototransduction "
                     "genes; rod panel score far above runner-up.",
    },
    # "1": {...},
}

print(f"Clusters needing an entry: {list(adata.obs[cfg.LEIDEN_KEY].cat.categories)}")
print(f"Entries provided so far:  {sorted(annotations)}")
'''),
    code('''\
annotation_table = annotation.build_annotation_table(adata, annotations)
io_utils.save_table(annotation_table, "cluster_annotations.csv")
display(annotation_table)

adata = annotation.apply_annotations(adata, annotation_table)
'''),
    code('''\
# Confidence audit: how many cells rest on weak calls?
audit = (
    annotation_table.groupby("confidence")["n_cells"].agg(["count", "sum"])
    .rename(columns={"count": "n_clusters", "sum": "n_cells"})
)
audit["pct_of_dataset"] = (100 * audit["n_cells"] / adata.n_obs).round(1)
display(audit)

low = annotation_table.loc[annotation_table["confidence"] == "low", "cluster"].tolist()
if low:
    print(f"Low-confidence clusters: {low}. Every conclusion that depends on these "
          "must be hedged in the Results section.")
'''),
    md("""
## Figure 3C — annotated UMAP
"""),
    code('''\
fig = plotting.figure_03_annotated_umap(adata)
'''),
    md("""
## 4. Cell-type proportions (research question 2)
"""),
    code('''\
proportions = annotation.cell_type_proportions(adata)
io_utils.save_table(proportions, "cell_type_proportions.csv")

by_condition = annotation.proportions_by_condition(proportions)
display(by_condition.pivot(index="cell_type", columns="condition",
                           values="mean_percent").fillna(0))
'''),
    code('''\
fig = plotting.figure_05_proportions(proportions, by_condition)
print("\\n" + annotation.PROPORTION_CAVEAT)
'''),
    md("""
### Interpretation — and the caveat that must travel with Figure 5

The caveat printed above is not boilerplate. Bise et al. explicitly attribute the
higher rod fraction in MNU-treated retinas to easier release of rods from a
damaged outer nuclear layer, i.e. a **capture effect**, not more rods. If the same
rise appears here, the honest statement is that rod *representation in the
library* increased, and that the data cannot distinguish this from a change in
tissue composition.

Note also the direction of the artefact: because proportions are compositional,
one cell type being over-captured mechanically depresses every other proportion.
A Müller glia percentage that falls after injury may reflect nothing but the rod
increase.
"""),
    code('''\
io_utils.save_checkpoint(adata, "annotated")
'''),
    md("""
### What to check before continuing

- [ ] Every cluster has an annotation entry with a real rationale.
- [ ] Müller glia are identified by identity markers, independently of EGFP.
- [ ] Ambiguous clusters are labelled `Unresolved`, not guessed.
- [ ] The RGC situation is recorded (found, or absent as in the paper).
- [ ] `tables/marker_genes.csv`, `cluster_annotations.csv`, `cell_type_proportions.csv` written.
- [ ] Figures 3 and 5 saved as PNG and PDF.
"""),
]


# =========================================================================== #
# step_06 -- EGFP / MG / photoreceptors
# =========================================================================== #

NB_06 = [
    md("""
# Step 06 — EGFP dynamics, Müller glia sub-states, rods and cones

**Purpose.** Answer research questions 3, 4 and 5.

## The positivity rule, stated once

A cell is **EGFP-positive** if its raw count for the transgene feature is
≥ `cfg.EGFP_POSITIVE_MIN_COUNTS` (default 1).

Justification: 3′ UMI data are sparse and a single-copy transgene yields low
counts, so any higher cut is arbitrary without evidence from the observed
distribution — which is why that distribution is plotted first. The continuous
log-normalised value is reported alongside the binary call throughout, so no
conclusion rests on the threshold alone.

## The interpretive guard

`careg:EGFP` reports **regenerative activation**, not cell identity. Bise et al.
found EGFP mostly in activated Müller glia and largely *absent* from the
proliferating progenitor clusters at 7 dpMNU — so EGFP⁺ and `pcna`⁺ are not
expected to coincide everywhere. An EGFP⁺ cell in a non-MG cluster is a finding to
examine (ambient RNA? doublet? genuine non-MG activity?), not a reason to relabel
the cluster.
"""),
    code(BOOTSTRAP),
    code('''\
import pandas as pd
adata = io_utils.load_checkpoint("annotated")
'''),
    md("""
## 1. Resolve the EGFP feature and call positivity
"""),
    code('''\
adata, egfp_name = egfp_analysis.add_egfp_columns(adata)

if egfp_name is None:
    print(
        "EGFP is not in this count matrix. Research question 3 and Figure 4 cannot "
        "be answered from these data. Report that explicitly in the Results section "
        "and do not substitute another gene."
    )
'''),
    code('''\
if egfp_name is not None:
    dist = egfp_analysis.egfp_count_distribution(adata)
    display(dist.head(15))
    print(
        "\\nIf almost all positive cells carry exactly 1 count, >0 is the only "
        "defensible threshold. If there is a clear gap in the distribution, a higher "
        "cut can be justified -- but then change cfg.EGFP_POSITIVE_MIN_COUNTS, record "
        "it in cfg.PARAM_OVERRIDES, and state the evidence in Methods."
    )
'''),
    md("""
## 2. EGFP across the time course (research question 3)
"""),
    code('''\
if egfp_name is not None:
    egfp_by_cond = egfp_analysis.egfp_by_condition(adata)
    display(egfp_by_cond[["condition", "sample", "percent_positive",
                          "mean_percent_positive", "min_percent_positive",
                          "max_percent_positive"]])

    egfp_table = egfp_analysis.egfp_summary(adata)
    io_utils.save_table(egfp_table, "egfp_summary.csv")
'''),
    code('''\
if egfp_name is not None:
    enrichment = egfp_analysis.egfp_enrichment_by_cluster(adata)
    io_utils.save_table(enrichment, "egfp_enrichment_by_cell_type.csv")
    display(enrichment)
'''),
    md("""
## Figure 4 — EGFP dynamics
"""),
    code('''\
if egfp_name is not None:
    fig = plotting.figure_04_egfp(adata, egfp_by_cond)
    fig = plotting.figure_04_activation_markers(adata)
'''),
    md("""
### Interpretation — comparison points, not targets

Bise et al. report, from their scRNA-seq: EGFP⁺ cells at 0.54% of control cells,
5.40% at 3 dpMNU, 2.64% at 7 dpMNU and 2.66% at 10 dpMNU, with ~10% of Müller glia
EGFP⁺ and MG far above every other cluster.

Three separate things to state, kept apart:

- **Observed result** — the percentages you actually measured, per replicate.
- **Comparison with the paper** — same direction? similar magnitude? peak at the
  same timepoint?
- **If they differ**, work through the candidate causes rather than asserting one:
  different normalisation (log vs SCTransform), no integration here, different
  clustering resolution, different QC thresholds, or a genuinely different
  transgene-detection rate. Some of these are checkable; say which.

Note that the guide's phrasing ("does expression subside by day 10") anticipates a
decline. The paper's own numbers show EGFP still at ~2.6% at day 10 — reduced from
the day-3 peak but not back to control. Report what you measure.
"""),
    md("""
## 3. Müller glia deep dive (research question 4)

Identity first: the subset is defined by the annotation, never by EGFP.
"""),
    code('''\
mg = egfp_analysis.subset_muller_glia(adata)
mg = egfp_analysis.recluster_subset(mg, resolution=0.3)
'''),
    code('''\
mg_evidence = egfp_analysis.mg_state_evidence(mg)
io_utils.save_table(mg_evidence.reset_index(), "mg_substate_evidence.csv")
display(mg_evidence)
print("\\n" + egfp_analysis.MG_STATE_GUIDANCE)
'''),
    code('''\
fig = plotting.figure_04_mg_umap(mg)
'''),
    md("""
### Interpretation — resist manufacturing three states

The question asks whether resting, activated and progenitor-like MG can be
distinguished. The defensible answers, in order of preference:

1. **Three states resolved** — one subcluster high on identity markers and low on
   activation; one keeping identity while gaining `ascl1a`/`her4.1`/EGFP; one
   losing identity and gaining `pcna`/`mki67`, enriched in injured samples.
2. **Two states resolved** — very common at this cell number. Report two.
3. **No sub-structure** — subclusters differ by depth or ribosomal content rather
   than by biology. That is a legitimate negative result: say the data do not
   resolve MG sub-states at this depth.

Progenitors may also not sit inside the MG cluster at all: if they have
transcriptionally moved away from MG identity, global clustering will have placed
them elsewhere. Check whether a `pcna`-high cluster exists outside this subset
before concluding that progenitors are absent.
"""),
    code('''\
# EGFP+ vs EGFP- Muller glia -- the analogue of the paper's 42-gene signature.
if egfp_name is not None:
    mg_types = [ct for ct in adata.obs["cell_type"].cat.categories
                if "muller" in str(ct).lower()]
    de_frames = [egfp_analysis.egfp_de_within_group(adata, ct) for ct in mg_types]
    de_frames = [d for d in de_frames if len(d)]
    if de_frames:
        mg_de = pd.concat(de_frames, ignore_index=True)
        io_utils.save_table(mg_de, "egfp_pos_vs_neg_muller_glia.csv")
        display(mg_de.head(30))
'''),
    md("""
## 4. Rods (research question 5)

The paper describes two rod populations — an immature-like cluster (high `rho`,
`pde6ga`, `guca1a`, plus `meig1`, `ppdpfa`, `rom1b`) and a mature-like one (high
`rhol`, `pde6gb`, `guca1b`, phototransduction machinery). The paralog usage is
inverted between them.

We do **not** import those labels. We re-cluster the rods, look at the same genes,
and report whether the split is reproduced.
"""),
    code('''\
rods, rod_evidence = egfp_analysis.rod_heterogeneity_evidence(adata)
io_utils.save_table(rod_evidence.reset_index(), "rod_subcluster_evidence.csv")
display(rod_evidence)
'''),
    md("""
### Interpretation

The decisive test is the **paralog inversion**: does one subcluster carry `rho` /
`pde6ga` / `guca1a` while another carries `rhol` / `pde6gb` / `guca1b`? That
pattern is specific and hard to produce by accident, so reproducing it is real
support for the paper's interpretation. `meig1` and `ppdpfa` restricted to the
immature-like subcluster would corroborate it.

If instead the subclusters differ mainly by total counts, gene number or
mitochondrial content, the split is technical and should be reported as such.

Note the ordering trap: an "immature" label implies a developmental trajectory
that a single snapshot cannot establish. Phrase it as *transcriptionally
immature-like*, and keep the developmental claim in the Discussion as an
interpretation of the paper's, not a result of yours.
"""),
    code('''\
# Injury response within rods: each timepoint against control.
rod_types = [ct for ct in adata.obs["cell_type"].cat.categories if "rod" in str(ct).lower()]
frames = []
for ct in rod_types:
    for cond in ["3dp", "7dp", "10dp"]:
        d = egfp_analysis.injury_response_de(adata, cell_type=ct, condition=cond)
        if len(d):
            frames.append(d.head(cfg.DE_TOP_N))
if frames:
    rod_de = pd.concat(frames, ignore_index=True)
    io_utils.save_table(rod_de, "rod_injury_response_de.csv")
    display(rod_de.groupby(["cell_type", "comparison"], observed=True).head(5))
'''),
    md("""
## 5. Cones
"""),
    code('''\
cones, cone_evidence = egfp_analysis.cone_subtype_evidence(adata)
io_utils.save_table(cone_evidence.reset_index(), "cone_subcluster_evidence.csv")
display(cone_evidence)
'''),
    code('''\
frames = []
cone_types = [ct for ct in adata.obs["cell_type"].cat.categories if "cone" in str(ct).lower()]
for ct in cone_types:
    for cond in ["3dp", "7dp", "10dp"]:
        d = egfp_analysis.injury_response_de(adata, cell_type=ct, condition=cond)
        if len(d):
            frames.append(d.head(cfg.DE_TOP_N))
if frames:
    cone_de = pd.concat(frames, ignore_index=True)
    io_utils.save_table(cone_de, "cone_injury_response_de.csv")
    display(cone_de.groupby(["cell_type", "comparison"], observed=True).head(5))
'''),
    md("""
### Interpretation — two limits to state plainly

1. **No recovery claim is available from these data.** The series ends at 10 days.
   The paper's structural restoration is at 30 dpMNU (rods, outer plexiform layer)
   and 40 dpMNU (UV cone outer segments), measured by immunofluorescence, not
   scRNA-seq. Whatever the 10-day transcriptome shows, it cannot demonstrate
   recovery.
2. **The DE tests are descriptive.** With two replicates per condition, a
   cell-level Wilcoxon test treats each cell as an independent sample and
   overstates significance — cells within a replicate are correlated. Use the
   ranking to identify candidate genes; do not present the adjusted p-values as
   population-level evidence. A pseudobulk test over the eight samples would be the
   correct design, and saying so is better than pretending the cell-level p-values
   are what they appear to be.
"""),
    md("""
## 6. Biological validation report
"""),
    code('''\
checks = {
    "1. Major retinal cell types detected":
        sorted(str(c) for c in adata.obs["cell_type"].cat.categories),
    "2. Muller glia identifiable":
        bool([c for c in adata.obs["cell_type"].cat.categories if "muller" in str(c).lower()]),
    "3. EGFP concentrated in the expected population":
        (egfp_analysis.egfp_enrichment_by_cluster(adata).iloc[0].to_dict()
         if egfp_name else "EGFP absent from matrix"),
    "4. EGFP changes across the time course":
        (egfp_analysis.egfp_by_condition(adata)
         .drop_duplicates("condition")[["condition", "mean_percent_positive"]]
         .to_dict("records") if egfp_name else "n/a"),
    "5. Proliferation markers present":
        [g for g in ["pcna", "mki67"] if g in adata.raw.var_names],
    "6. Rod subclusters found": int(rods.obs["subcluster"].nunique()),
    "7. Cone subclusters found": int(cones.obs["subcluster"].nunique()),
    "8. Composition shifts": "see tables/cell_type_proportions.csv (capture-bias caveat applies)",
    "9. Replicate vs condition effect": "see tables/batch_diagnostics.csv",
}
for key, value in checks.items():
    print(f"{key}\\n    {value}\\n")
'''),
    code('''\
validation = pd.DataFrame([
    {"question": k, "answer": str(v)} for k, v in checks.items()
])
io_utils.save_table(validation, "biological_validation.csv")

mg.write_h5ad(cfg.RESULTS_DIR / "06_muller_glia.h5ad", compression="gzip")
io_utils.save_checkpoint(adata, "mg_egfp")
'''),
    md("""
### What to check before continuing

- [ ] The EGFP threshold is justified from the observed count distribution.
- [ ] EGFP⁺ fractions are reported per replicate, not only pooled.
- [ ] MG sub-states are reported at the number the data support — two is a valid answer.
- [ ] Rod paralog inversion is either reproduced or reported as not reproduced.
- [ ] No recovery claim appears anywhere; the series stops at day 10.
- [ ] The pseudobulk limitation on DE is stated in the Discussion.
- [ ] Every table in `tables/` is written and every figure exists as PNG and PDF.
"""),
]


NOTEBOOKS = {
    "step_0.0_Environment_Management_with_uv.ipynb": NB_00,
    "step_01_Loading_Libraries_and_10x_Data.ipynb": NB_01,
    "step_02_Quality_Control_and_Cell_Filtering.ipynb": NB_02,
    "step_03_Normalization_HVG_and_Scaling.ipynb": NB_03,
    "step_04_PCA_UMAP_and_Clustering.ipynb": NB_04,
    "step_05_Cell_Type_Annotation_and_Marker_Discovery.ipynb": NB_05,
    "step_06_EGFP_and_Muller_Glia_Dynamics.ipynb": NB_06,
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true",
                        help="overwrite notebooks that already contain outputs")
    args = parser.parse_args()
    for filename, cells in NOTEBOOKS.items():
        write_notebook(filename, cells, force=args.force)
    print(f"\n{len(NOTEBOOKS)} notebooks in {NOTEBOOK_DIR.relative_to(REPO_ROOT)}/")


if __name__ == "__main__":
    main()
